x-app: &default-app
  build:
    context: .
    dockerfile: Dockerfile
    target: "local"

x-env: &env
  env_file:
    - .env


services:
  db:
    <<: *env
    build:
      context: ./postgres-extensions-docker
      dockerfile: Dockerfile
      args:
        POSTGRES_VERSION: "17"
        TIMESCALEDB_VERSION: "2.18.0"
        PGVECTOR_VERSION: "0.8.0"
        AGE_VERSION: "1.5.0"
    container_name: postgres-ext-dev
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=${POSTGRES_PORT}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - nzt_postgres_data:/var/lib/postgresql/data
      - ./postgres-extensions-docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    shm_size: "256mb"
    healthcheck:
      test: pg_isready -d ${POSTGRES_NAME} -U ${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nzt-backend-network
  redis:
      image: redis:7-alpine
      container_name: nzt-backend-redis-dev
      volumes:
      - nzt_backend_redis_data:/var/lib/redis/data
      healthcheck:
        test: redis-cli ping
        interval: 1s
        timeout: 3s
        retries: 50
      networks:
        - nzt-backend-network
  app:
    <<: 
     - *env
     - *default-app
    container_name: nzt-backend-dev
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - nzt-backend-network

volumes:
  nzt_postgres_data:
  nzt_backend_redis_data:

networks:
  nzt-backend-network: