"""added role to raw message table

Revision ID: a8f445f643cc
Revises: bafd8cfe0286
Create Date: 2026-07-07 16:38:57.989762

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8f445f643cc"
down_revision: Union[str, Sequence[str], None] = "bafd8cfe0286"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "raw_messages", sa.Column("role", sa.String(length=15), nullable=False)
    )
    op.create_index(
        "idx_raw_messages_user_timestamp",
        "raw_messages",
        ["user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_raw_messages_user_timestamp", table_name="raw_messages")
    op.drop_column("raw_messages", "role")
    # ### end Alembic commands ###
