"""fix_memory_schema_and_add_indexes

Revision ID: bafd8cfe0286
Revises: 6dd1cb3fd706
Create Date: 2026-06-28 11:46:43.212316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = "bafd8cfe0286"
down_revision: Union[str, Sequence[str], None] = "6dd1cb3fd706"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_relation_types",
        sa.Column("name", sa.String(length=65), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_preset", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_accepted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_relation_types")),
        sa.UniqueConstraint("name", name=op.f("uq_entity_relation_types_name")),
    )
    op.create_table(
        "users",
        sa.Column("time_zone", sa.String(length=100), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("username", sa.String(length=65), nullable=True),
        sa.Column("mobile_phone", sa.String(length=16), nullable=True),
        sa.Column("address", sa.String(length=125), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("USER", "MODERATOR", "ADMIN", name="userroles"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "auth_identities",
        sa.Column(
            "provider",
            sa.Enum(
                "VK",
                "EMAIL",
                "GOOGLE",
                "INSTAGRAM",
                "TELEGRAM",
                "APPLE",
                name="useridentitiesproviders",
            ),
            nullable=False,
        ),
        sa.Column("provider_user_id", sa.String(), nullable=False),
        sa.Column("profile", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_auth_identities_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_identities")),
        sa.UniqueConstraint("user_id", "provider_user_id", name="uq_user_provider"),
    )
    op.create_index(
        op.f("ix_auth_identities_user_id"), "auth_identities", ["user_id"], unique=False
    )
    op.create_table(
        "connection_channels",
        sa.Column(
            "channel",
            sa.Enum("PHONE", "WEB", "TELEGRAM", "DESKTOP", name="connectionchannels"),
            nullable=False,
        ),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_connection_channels_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connection_channels")),
    )
    op.create_index(
        op.f("ix_connection_channels_user_id"),
        "connection_channels",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "embeddings",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("embeddable_uuid", sa.Uuid(), nullable=True),
        sa.Column("embeddable_id", sa.Integer(), nullable=True),
        sa.Column("embeddable_type", sa.String(length=20), nullable=False),
        sa.Column("embedding", VECTOR(dim=1536), nullable=False),
        sa.Column("model_version", sa.String(length=50), nullable=False),
        sa.Column("model_provider", sa.String(length=50), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=True),
        sa.Column("total_chunks", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(embeddable_uuid IS NOT NULL AND embeddable_id IS NULL) OR (embeddable_uuid IS NULL AND embeddable_id IS NOT NULL)",
            name=op.f("ck_embeddings_ck_exactly_one_id"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_embeddings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embeddings")),
    )
    op.create_index(
        "ix_embeddings_lookup",
        "embeddings",
        ["embeddable_type", "embeddable_id"],
        unique=False,
    )
    op.create_index(
        "ix_embeddings_model",
        "embeddings",
        ["model_provider", "model_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_embeddings_user_id"), "embeddings", ["user_id"], unique=False
    )
    op.create_index(
        "ix_embeddings_vector",
        "embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "raw_messages",
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_raw_messages_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_messages")),
    )
    op.create_index(
        op.f("ix_raw_messages_user_id"), "raw_messages", ["user_id"], unique=False
    )
    op.create_table(
        "entities",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "PERSON",
                "ORGANIZATION",
                "PROJECT",
                "PRODUCT",
                "LOCATION",
                "ASSET",
                "CONCEPT",
                "IDENTITY",
                "GOAL",
                name="entitytypes",
            ),
            nullable=False,
        ),
        sa.Column("aliases", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("importance_score", sa.DECIMAL(precision=3, scale=0), nullable=False),
        sa.Column("raw_message_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "importance_score = ANY(ARRAY[0, 25, 50, 70, 85, 95, 99])",
            name=op.f("ck_entities_ck_entities_importance_score"),
        ),
        sa.ForeignKeyConstraint(
            ["raw_message_id"],
            ["raw_messages.id"],
            name=op.f("fk_entities_raw_message_id_raw_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_entities_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
    )
    op.create_index(
        op.f("ix_entities_entity_type"), "entities", ["entity_type"], unique=False
    )
    op.create_index(op.f("ix_entities_name"), "entities", ["name"], unique=False)
    op.create_index(
        op.f("ix_entities_raw_message_id"), "entities", ["raw_message_id"], unique=False
    )
    op.create_index(op.f("ix_entities_user_id"), "entities", ["user_id"], unique=False)
    op.create_index(
        "ix_entities_user_type", "entities", ["user_id", "entity_type"], unique=False
    )
    op.create_table(
        "entity_relation_type_suggestions",
        sa.Column("entity_relation_type_id", sa.Integer(), nullable=False),
        sa.Column("raw_message_id", sa.Integer(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_relation_type_id"],
            ["entity_relation_types.id"],
            name=op.f(
                "fk_entity_relation_type_suggestions_entity_relation_type_id_entity_relation_types"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_message_id"],
            ["raw_messages.id"],
            name=op.f(
                "fk_entity_relation_type_suggestions_raw_message_id_raw_messages"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_entity_relation_type_suggestions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_relation_type_suggestions")),
    )
    op.create_index(
        op.f("ix_entity_relation_type_suggestions_entity_relation_type_id"),
        "entity_relation_type_suggestions",
        ["entity_relation_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_relation_type_suggestions_raw_message_id"),
        "entity_relation_type_suggestions",
        ["raw_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_relation_type_suggestions_user_id"),
        "entity_relation_type_suggestions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_entity_relation_type_suggestions_user_status",
        "entity_relation_type_suggestions",
        ["user_id", "status"],
        unique=False,
    )
    op.create_table(
        "events",
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("importance_score", sa.DECIMAL(precision=3, scale=0), nullable=False),
        sa.Column("raw_message_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "importance_score = ANY(ARRAY[0, 25, 50, 70, 85, 95, 99])",
            name=op.f("ck_events_ck_events_importance_score"),
        ),
        sa.ForeignKeyConstraint(
            ["raw_message_id"],
            ["raw_messages.id"],
            name=op.f("fk_events_raw_message_id_raw_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_events_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(
        op.f("ix_events_raw_message_id"), "events", ["raw_message_id"], unique=False
    )
    op.create_index(op.f("ix_events_user_id"), "events", ["user_id"], unique=False)
    op.create_index(
        "ix_events_user_timestamp", "events", ["user_id", "timestamp"], unique=False
    )
    op.create_table(
        "events_entities_relations",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_events_entities_relations_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_events_entities_relations_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "entity_id", "event_id", name=op.f("pk_events_entities_relations")
        ),
    )
    op.create_table(
        "relationships_history",
        sa.Column("from_entity_id", sa.Uuid(), nullable=False),
        sa.Column("to_entity_id", sa.Uuid(), nullable=False),
        sa.Column("rel_type", sa.String(length=65), nullable=False),
        sa.Column(
            "valid_from",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "from_entity_id != to_entity_id",
            name=op.f("ck_relationships_history_ck_no_self_relation"),
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from",
            name=op.f("ck_relationships_history_ck_valid_period"),
        ),
        sa.ForeignKeyConstraint(
            ["from_entity_id"],
            ["entities.id"],
            name=op.f("fk_relationships_history_from_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_entity_id"],
            ["entities.id"],
            name=op.f("fk_relationships_history_to_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_relationships_history_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationships_history")),
        sa.UniqueConstraint(
            "from_entity_id", "to_entity_id", "valid_from", name="uq_relationship"
        ),
    )
    op.create_index(
        "ix_relationships_from_to",
        "relationships_history",
        ["from_entity_id", "to_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_relationships_history_from_entity_id"),
        "relationships_history",
        ["from_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_relationships_history_to_entity_id"),
        "relationships_history",
        ["to_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_relationships_history_user_id"),
        "relationships_history",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_relationships_rel_type", "relationships_history", ["rel_type"], unique=False
    )
    op.create_index(
        "ix_valid_period",
        "relationships_history",
        ["valid_from", "valid_to"],
        unique=False,
        postgresql_using="btree",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_valid_period", table_name="relationships_history", postgresql_using="btree"
    )
    op.drop_index("ix_relationships_rel_type", table_name="relationships_history")
    op.drop_index(
        op.f("ix_relationships_history_user_id"), table_name="relationships_history"
    )
    op.drop_index(
        op.f("ix_relationships_history_to_entity_id"),
        table_name="relationships_history",
    )
    op.drop_index(
        op.f("ix_relationships_history_from_entity_id"),
        table_name="relationships_history",
    )
    op.drop_index("ix_relationships_from_to", table_name="relationships_history")
    op.drop_table("relationships_history")
    op.drop_table("events_entities_relations")
    op.drop_index("ix_events_user_timestamp", table_name="events")
    op.drop_index(op.f("ix_events_user_id"), table_name="events")
    op.drop_index(op.f("ix_events_raw_message_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(
        "ix_entity_relation_type_suggestions_user_status",
        table_name="entity_relation_type_suggestions",
    )
    op.drop_index(
        op.f("ix_entity_relation_type_suggestions_user_id"),
        table_name="entity_relation_type_suggestions",
    )
    op.drop_index(
        op.f("ix_entity_relation_type_suggestions_raw_message_id"),
        table_name="entity_relation_type_suggestions",
    )
    op.drop_index(
        op.f("ix_entity_relation_type_suggestions_entity_relation_type_id"),
        table_name="entity_relation_type_suggestions",
    )
    op.drop_table("entity_relation_type_suggestions")
    op.drop_index("ix_entities_user_type", table_name="entities")
    op.drop_index(op.f("ix_entities_user_id"), table_name="entities")
    op.drop_index(op.f("ix_entities_raw_message_id"), table_name="entities")
    op.drop_index(op.f("ix_entities_name"), table_name="entities")
    op.drop_index(op.f("ix_entities_entity_type"), table_name="entities")
    op.drop_table("entities")
    op.drop_index(op.f("ix_raw_messages_user_id"), table_name="raw_messages")
    op.drop_table("raw_messages")
    op.drop_index(
        "ix_embeddings_vector",
        table_name="embeddings",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(op.f("ix_embeddings_user_id"), table_name="embeddings")
    op.drop_index("ix_embeddings_model", table_name="embeddings")
    op.drop_index("ix_embeddings_lookup", table_name="embeddings")
    op.drop_table("embeddings")
    op.drop_index(
        op.f("ix_connection_channels_user_id"), table_name="connection_channels"
    )
    op.drop_table("connection_channels")
    op.drop_index(op.f("ix_auth_identities_user_id"), table_name="auth_identities")
    op.drop_table("auth_identities")
    op.drop_table("users")
    op.drop_table("entity_relation_types")
    # ### end Alembic commands ###
