apiVersion: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: RequestID
          matcherRegex: "request_id\":\\\"([^\\\"]+)\\\""
          url: "$${__value.raw}"
          datasourceUid: loki
        - name: UserID
          matcherRegex: "user_id\":\\\"([^\\\"]+)\\\""
          url: "$${__value.raw}"
          datasourceUid: loki